<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2019 广东卓锐软件有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------

namespace app\admin\controller;

use think\Db;
use think\Validate;

/**
 * 后台公共控制器
 * @package app\admin\controller
 */
class GenerateApi extends Admin
{
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->assign('_js_files',['select2_js']);
        $this->assign('_css_files',['select2_css']);
        $this->assign('_js_init',"['select2']");
    }

    /**
     * 首页列表
     * @return mixed
     */
    function index()
    {
        $db_name = config('database.database');
        $tables = Db::query("SELECT TABLE_NAME,TABLE_COMMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA = '{$db_name}'");
        $this->assign('tables',$tables);

        return $this->fetch();
    }

    /**
     * 代码生成
     */
    function generate()
    {
        if(!$this->request->isAjax()) $this->error('错误的请求方式');
        $data = input();
       //数据校验
       $validate = new Validate([
           'module' => 'require',
           'temp_type' => 'require',
           'tables' => 'require',
           'class_name' => 'require',
           'name' => 'require',
           'is_method' => 'require',
       ]);
       if(!$validate->check($data)){
            $this->error($validate->getError());
       }
       //过滤有效数据

       foreach ($data['field_checkbox'] as $key => $item){
           if($item == 'on'){

           }else{
               unset($data['field_checkbox'][$key]);
           }
       }





      echo 'ss';


    }

    /**
     * 获取table的字段列表
     */
    function get_table_filed()
    {
        if (!$this->request->isAjax()) $this->error('错误的请求方式');
        $tables =  input('tables','');
        $tables = json_decode($tables,true);
        if(!$tables){
            $this->error('请选择需要查询的表');
        }

        $db_name = config('database.database');
        $tables = preg_replace('/,/i',"','",implode(',',$tables));
        $tables = "'".$tables."'";
        $tables = Db::query("SELECT concat(TABLE_NAME,'_',COLUMN_NAME) as FIELD,TABLE_NAME,COLUMN_NAME,COLUMN_COMMENT,IS_NULLABLE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = '{$db_name}' and TABLE_NAME in({$tables})");

        $this->success('成功','',$tables);
    }
}   
        